name: Image CI

on:
  push:
    branches:
    - 'myfork'
    paths:
    - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "IceCodeNew/installer"
          ref: "myfork"

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: pre-start
        shell: bash
        run: |
          curl() { $(type -P curl) -LRq --retry 5 --retry-delay 10 --retry-max-time 60 --fail "$@"; }
          curl -o '.ko.yaml' -- \
              https://raw.githubusercontent.com/IceCodeNew/docker-collections/master/default.ko.yaml

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: ko-build/setup-ko@v0.8
        env:
          KO_DOCKER_REPO: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/installer
      - run: ko build --platform=linux/amd64,linux/arm64 --bare ./